services:
  express:
    build:
      context: ./Express-server
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://toledo:123@mongo:27017/CrudUsuarios?authSource=admin
    volumes:
      - ./Express-server:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: toledo
      MONGO_INITDB_ROOT_PASSWORD: "123"
      MONGO_INITDB_DATABASE: CrudUsuarios
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: